ALTER TABLE murm_user ADD
(
    profile_image_blob      BLOB,
    profile_image_mime_type VARCHAR2(200),
    profile_image_filename  VARCHAR2(500)
);

CREATE TABLE foto_post
(
    id                    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_foto_post PRIMARY KEY,
    user_id               NUMBER         NOT NULL,
    photo_day             DATE           DEFAULT TRUNC(CURRENT_DATE) NOT NULL,
    caption               VARCHAR2(1000),
    image_blob            BLOB           NOT NULL,
    image_mime_type       VARCHAR2(200)  NOT NULL,
    image_filename        VARCHAR2(500),
    published_at          TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at            TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_foto_post_user FOREIGN KEY (user_id) REFERENCES murm_user(id) ON DELETE CASCADE,
    CONSTRAINT uk_foto_post_user_day UNIQUE (user_id, photo_day)
);

CREATE TABLE foto_comment
(
    id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_foto_comment PRIMARY KEY,
    post_id     NUMBER         NOT NULL,
    user_id     NUMBER         NOT NULL,
    message     VARCHAR2(500)  NOT NULL,
    created_at  TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_foto_comment_post FOREIGN KEY (post_id) REFERENCES foto_post(id) ON DELETE CASCADE,
    CONSTRAINT fk_foto_comment_user FOREIGN KEY (user_id) REFERENCES murm_user(id) ON DELETE CASCADE
);

CREATE TABLE foto_friend
(
    user_id         NUMBER      NOT NULL,
    friend_user_id  NUMBER      NOT NULL,
    status          CHAR(1)     DEFAULT 'A' NOT NULL,
    created_at      TIMESTAMP   DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_foto_friend PRIMARY KEY (user_id, friend_user_id),
    CONSTRAINT fk_foto_friend_user FOREIGN KEY (user_id) REFERENCES murm_user(id) ON DELETE CASCADE,
    CONSTRAINT fk_foto_friend_friend FOREIGN KEY (friend_user_id) REFERENCES murm_user(id) ON DELETE CASCADE,
    CONSTRAINT ck_foto_friend_status CHECK (status IN ('P', 'A', 'B')),
    CONSTRAINT ck_foto_friend_distinct CHECK (user_id <> friend_user_id)
);

CREATE INDEX ix_foto_post_published_at ON foto_post (published_at DESC);
CREATE INDEX ix_foto_comment_post ON foto_comment (post_id, created_at);
CREATE INDEX ix_foto_friend_friend ON foto_friend (friend_user_id, status);
